name: glowme
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^12.1.0
  animated_splash_screen: ^1.3.0
  page_transition: ^2.1.0
  google_fonts: ^6.1.0
  path_provider: ^2.1.1
  pinput: ^3.0.1
  carousel_slider: ^4.2.1
  carousel_indicator: ^1.0.6
  flutter_svg: ^2.0.9
  flutter_date_pickers: ^0.4.2
  table_calendar: ^3.0.9
  flutter_rounded_date_picker: ^3.0.4
  provider: ^6.1.1
  json_serializable: ^6.7.1
  smooth_page_indicator: ^1.1.0
  fluttertoast: ^8.2.4
  shared_preferences: ^2.2.2
  flutter_map: ^6.1.0
  latlng: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  build_runner: ^2.4.7


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf